### ISSUE TITLE
YarpJS + WebGL

### ISSUE THREAD

**Issue by pattacini** [cciliber/YarpJS#3]
Very nice job dude! We should move this repo to [**robotology**](https://github.com/robotology) asap!

##### Question

How easy would it be to create a self contained web based application using **YarpJS** as _back-end_ and a **WebGL** _front-end_ (there are plenty examples out there, e.g. [**three.js**](https://github.com/mrdoob/three.js/)) to visualize streams of **3D point clouds** within a convenient UI?

I bet this application will guarantee YarpJS big success in our lab and consequently a widespread dissemination :smile:

**Comment by cciliber** [comment]
That's cool 👍  and I believe it would take veeeery little time to implement...

Actually this would go for a very nice demo to add in the [README](https://github.com/cciliber/YarpJS/blob/master/README.md)

I'll get back to you as soon as I have news : D

**Comment by cciliber** [comment]
Ok, update. I have added a small [demo](https://github.com/cciliber/YarpJS/blob/master/README.md#example-visualization-with-WebGL) showing how one can use three.js to visualize information received through yarp.

Regarding point clouds I didn't really spend much time reading three.js docs, but I believe it wouldn't take much to update my demo to visualize point clouds.

**Comment by pattacini** [comment]
Saw the demo: quite cool indeed!
Thanks a lot and get ready for a live presentation of your work here :smile:

**Comment by cciliber** [comment]
Create a demo where a 3D point cloud can be dynamically created from data received from a yarp port

**Comment by cciliber** [comment]
Ok @pattacini, I have added a new example (not documented yet though) showing an example of point cloud dynamically built by sending point by point through a yarp port. This should be what you asked long ago :)

**Comment by pattacini** [comment]
Cool! That's great.

`point-by-point` or a message containing the entire point-cloud? The latter is way preferable :smile: 

Also, does the point cloud get updated by sending another message?

**Comment by cciliber** [comment]
- yes, for now is just point-by-point but setting it to a variable number is very easy.

- by updating you mean that the point cloud changes in real time? Then yes. :)

**Comment by pattacini** [comment]
Great, thanks!
