### ISSUE TITLE
Port Audio

### ISSUE THREAD

**Issue by cciliber** [cciliber/YarpJS#5]
Create a [port audio](http://wiki.icub.org/wiki/Grabbing_sound_with_PortAudio) wrapper for YarpJS

**Comment by cciliber** [comment]
Ok, done in 4c181ab14b5f819e013695df460ced3e20aa5145

Maybe of interest for @vtikha?

**Comment by vtikha** [comment]
Excellent!!!! Can't wait to try it out!!
