### ISSUE TITLE
Error while compiling on Ubuntu 14.04

### ISSUE THREAD

**Issue by vtikha** [cciliber/YarpJS#6]
@cciliber While compiling '''YarpJS''' on an ubuntu machine I am getting the following error:

`[  9%] Building CXX object CMakeFiles/YarpJS.dir/YarpJS/src/_YarpJS_SelfRegister.cpp.o
In file included from /usr/local/src/robot/YarpJS/YarpJS/src/_YarpJS_SelfRegister.cpp:11:0:
/usr/local/src/robot/YarpJS/YarpJS/include/YarpJS_RPCPort.h: In constructor 'YarpJS_RPCPort::YarpJS_RPCPort(const Nan::FunctionCallbackInfo<v8::Value>&)':
/usr/local/src/robot/YarpJS/YarpJS/include/YarpJS_RPCPort.h:198:25: error: no matching function for call to 'YarpJS_RPCPort::YarpJS_RPCPort()'
         :YarpJS_RPCPort()
                         ^
/usr/local/src/robot/YarpJS/YarpJS/include/YarpJS_RPCPort.h:198:25: note: candidate is:
/usr/local/src/robot/YarpJS/YarpJS/include/YarpJS_RPCPort.h:157:7: note: YarpJS_RPCPort::YarpJS_RPCPort(const YarpJS_RPCPort&) <deleted>
 class YarpJS_RPCPort :  public YarpJS,
       ^
/usr/local/src/robot/YarpJS/YarpJS/include/YarpJS_RPCPort.h:157:7: note:   candidate expects 1 argument, 0 provided
make[2]: *** [CMakeFiles/YarpJS.dir/YarpJS/src/_YarpJS_SelfRegister.cpp.o] Error 1
make[1]: *** [CMakeFiles/YarpJS.dir/all] Error 2
make: *** [all] Error 2
`

any idea?

**Comment by cciliber** [comment]
Try to remove de build folder and cmake-js from scratch

**Comment by vtikha** [comment]
Altrady tried it...

**Comment by cciliber** [comment]
Fixed, apparently I was using a C++11 feature (thanks @pattacini for pointing that out :) )

**Comment by vtikha** [comment]
👍
